apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeder-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeder
  template:
    metadata:
      labels:
        app: feeder
    spec:
      containers:
        - name: feeder
          image: sebbyfay/feeder
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://bounce_dev:bounce_dev1@cluster0.xmmui.mongodb.net/bounce_dev1?retryWrites=true&w=majority'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: feeder-srv
spec:
  selector:
    app: feeder
  ports:
    - name: feeder
      protocol: TCP
      port: 3000
      targetPort: 3000
